### ISSUE TITLE
Compare Accent List

### ISSUE THREAD

**Issue by jag3773** [openscriptures/morphhb-parsing#1]
@AndyHubert Compare the accent list here https://github.com/openscriptures/morphhb/blob/master/oxlos-import/ConvertWLC.py#L44 with what you have here:  https://github.com/openscriptures/morphhb-parsing/blob/58c049c13146d8993a571797e8faa21adbd229f7/morphhb-scripts/utils.js#L133

The list in that python file is a lot longer than yours, I wonder if we'd get better matching by using that extended set of accents?

**Comment by AndyHubert** [comment]
My list actually contains more because it contains a range \u0591-\u05AF which covers all but one from the other list, plus 4 more characters. I am quite confident it gets rid of all the accent characters.

**Comment by jag3773** [comment]
Great, I missed that range in the list!
