### ISSUE TITLE
Member ID to Use

### ISSUE THREAD

**Issue by jag3773** [openscriptures/morphhb-parsing#2]
@AndyHubert Let's use a special member id that we create as a new account in the system when we get to this point: 
https://github.com/openscriptures/morphhb-parsing/blob/58c049c13146d8993a571797e8faa21adbd229f7/morphhb-scripts/scripts/auto_parse.js#L7

**Comment by AndyHubert** [comment]
I actually already created a new account that I will not use to parse, but just for this. The memberId is 416 and thus the `updateMainTables.js` script puts in new entries to the notes table under this memberId. Those entries are then deleted before the script is rerun.
